### ISSUE TITLE
StatusCodeError: 504 - "{\"message\": \"Endpoint request timed out\"}"

### ISSUE THREAD

**Issue by Alexa-RR** [edencomputing/attprefabulator#24]
Every time I try to access my server I get a 504 
![image](https://user-images.githubusercontent.com/53471801/125660954-58ab6aa3-dcd2-4efd-8ac1-2ea5c1904c90.png)

**Comment by edencomputing** [comment]
Hi Alexa,

There have been several problems at Alta's datacenters over the last couple of days due to the quest release, and my first suscpicion is that the server was actually not connectable when you tried.  Were you able to use the official dashboard to connect while this was happening?

For clarity, are you trying to connect to a PC server or a Quest account server?  The latter will not work at this time unfortunately.

-- Pat

**Comment by Alexa-RR** [comment]
> Hi Alexa,
> 
> There have been several problems at Alta's datacenters over the last couple of days due to the quest release, and my first suscpicion is that the server was actually not connectable when you tried. Were you able to use the official dashboard to connect while this was happening?
> 
> For clarity, are you trying to connect to a PC server or a Quest account server? The latter will not work at this time unfortunately.
> 
> -- Pat

I tried connecting to both my quest and my PC servers and I wasn't able to connect to both, I was able to access my servers though http://dashboard.townshiptale.com/

**Comment by edencomputing** [comment]
This is indeed a problem with Alta's API servers having issues keeping up with the inrush of new servers being created by quest users.  Give this a day or two to calm down and you should be able to connect again.

**Comment by Alexa-RR** [comment]
Okay, thank you ❤️

**Comment by TwidgeVR** [comment]
Hi again!

Please try out the version v1.8.2 I just released, which should work around the API problem.  Good luck!
