### ISSUE TITLE
Make an android version 

### ISSUE THREAD

**Issue by amitdvir1122** [edencomputing/attprefabulator#4]
The title says it all

**Comment by edencomputing** [comment]
It's not in my scope, but since this is just javascript it could probably be repackaged by anyone willing to take on the task.

There's another option; it actually runs as a web service on your PC on port 21129 by default.  You can run the app on your PC, and then browse to it on your local network from your Android device at http://<your PC's ip>:21129

Note you may need a firewall rule or exception on your PC to accept the traffic, though this port should be open by default.

**Comment by amitdvir1122** [comment]
Okey great thank you
